apiVersion: v1
kind: Pod
metadata:
  name: gcp-gke-monitor-test
  labels:
    name: gcp-gke-monitor-test
spec:
  containers:
  - image: docker.io/brianeiler/gcp-gke-monitor-test:latest
    name: gcp-gke-monitor-test
    ports:
    - containerPort: 8080
      protocol: TCP
    env:
    - name: POD_ID
      valueFrom:
        fieldRef:
          fieldPath: metadata.uid
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: NAMESPACE_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: gcp-gke-monitor-test
  name: gcp-gke-monitor-test-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: gcp-gke-monitor-test
  type: LoadBalancer
